Repository Data-Science-and-Society-2026/simulation_exercise, pull requests merged in 2025-02, with the labels that each got.

#9 initial Makefile setup for issue #8
  .gitignore
  .python-version
  Makefile
  Makefiles/darwin/system_dependencies.sh
  Makefiles/windows/system_dependencies.ps1
  pyproject.toml
  uv.lock
Labels: Dev-ops

#11 updating the README.md for teams setup for #10
  README.md
Labels: documentation, Dev-ops

#13 fix powershell script for #12
  Makefile
Labels: bug, Dev-ops

#7 Move AI tutor functionality to a new module and clean up the project …
  ai_rag/Ollama_trial_1.py
  ai_rag/README.md
Labels: enhancement, AI-Rag

#23 Clean repo
  Ollama_trial_1.py
  README.md
  ai_rag/Ollama_trial_1.py
  main.py
  stt_tts/README.md
  stt_tts/tts_functions.py
Labels: enhancement
